###
GET http://localhost:1337/information
accept: application/json

### 
GET http://localhost:1337/information/1
accept: application/json

###
GET http://localhost:1337/sportnews
accept: application/json

### 
GET http://localhost:1337/sportnews/1
accept: application/json

### 
GET http://localhost:1337/product
accept: application/json

### 
GET http://localhost:1337/fakes
accept: application/json

### 
GET http://localhost:1337/pvprules
accept: application/json