###
GET http://localhost:1337/information?_sort=权重:DESC
###
GET http://localhost:1337/information?类型=热点资讯

### 
GET http://localhost:1337/information/4

###
GET http://localhost:1337/sportnews?类型=行业新闻

### 
GET http://localhost:1337/sportnews/1

### 
GET http://localhost:1337/product

### 
GET http://localhost:1337/fakes
### 
GET http://localhost:1337/fakes/1

### 
GET http://localhost:1337/pvprules
### 
GET http://localhost:1337/pvprules/1

### 
GET http://localhost:1337/cests
### 
GET http://localhost:1337/cests/1

### 
GET http://localhost:1337/headerbanner

### 
GET http://localhost:1337/slider

### 
GET http://localhost:1337/rightbanner

### 
GET http://localhost:1337/columnbanner

### 
GET http://localhost:1337/friendlink

### 
GET http://localhost:1337/siteinfo
### 
GET http://localhost:1337/menu
### 
GET http://localhost:1337/footer

### 
GET http://localhost:1337/copyright